### ISSUE TITLE
Add support for namespace imports

### ISSUE THREAD

**Issue by johno** [mdx-js/mdx#1050] opened 2020-05-01 14:17 UTC
```js
import * as Foo from './bar'
```

**Comment by ankeetmaini** [comment] 2020-05-02 04:38
I can take a stab at it!

**Comment by johno** [comment] 2020-05-06 15:27
That'd be great @ankeetmaini ankeetmaini! Let us know if you have any questions!

**Comment by apipkin** [comment] 2020-05-19 14:45
I am curious if this is the same issue I'm having when using `<Examples.ButtonGroup />` in my mdx files. It tells me it cannot find Examples. 

Here's a reproduction of the issue if this helps the effort! https://github.com/apipkin/gastby-issue-1

**Comment by ankeetmaini** [comment] 2020-05-19 17:12
@johno I am new to this codebase. Will this change belong in the `mdx` package or the babel plugin? Will try and get some early feedback by this weekend.

**Comment by johno** [comment] 2020-05-19 17:19
Great, it'll be in the babel plugin @ankeetmaini 

@apipkin I have a WIP PR that fixes the bug you're referring to here: https://github.com/mdx-js/mdx/pull/953

**Comment by apipkin** [comment] 2020-05-19 17:58
@johno Awesome! Thanks!

**Comment by wooorm** [comment] 2020-12-18 16:08
Hi all! I’m going to close this as it landed on the `main`, the (now default) branch we’re using to gear up to the MDX@2 release.

The reason is so that it’s more clear which issues still need to be solved already and don’t require further work.

Expect another `next` release soonish, which might include it, or maybe it’s already released as a beta!

For more info, see <https://github.com/mdx-js/mdx/issues/1041>.

**Closed by wooorm** 2020-12-18 16:08 UTC
Labels: 💎 v2, 🙆 status/confirmed, 🦋 type/enhancement
