### ISSUE TITLE
Custom webpack setup fails

### ISSUE THREAD

**Issue by leifriksheim** [mdx-js/mdx#478] opened 2019-03-21 00:10 UTC
### Can't seem to import mdx files with custom webpack setup

I can't seem to be able to import a .mdx file in my custom webpack setup:

```
import MyComponent from "./MyComponent.mdx";
```

### Enviroment

*   macOS Mojave
*   node 10.13.0, npm 6.9.0

`package.json`:

```
"devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.4.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.4.0",
    "@babel/preset-env": "^7.4.1",
    "@babel/preset-react": "^7.0.0",
    "@mdx-js/loader": "^0.20.3",
    "babel-loader": "^8.0.5",
    "css-loader": "^1.0.0",
    "html-webpack-plugin": "^3.2.0",
    "style-loader": "^0.23.0",
    "webpack": "^4.19.1",
    "webpack-cli": "^3.1.1",
    "webpack-dev-server": "^3.1.8"
  },
  "dependencies": {
    "@babel/polyfill": "^7.4.0",
    "react": "^16.5.2",
    "react-dom": "^16.5.2"
  }
```

`webpack.config.js`:

```
const HtmlWebPackPlugin = require("html-webpack-plugin");

module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      },
      {
        test: /\.css$/,
        use: [
          {
            loader: "style-loader"
          },
          {
            loader: "css-loader",
            options: {
              importLoaders: 1,
              localIdentName: "[name]_[local]_[hash:base64]",
              sourceMap: true,
              minimize: true
            }
          }
        ]
      },
      {
        test: /.mdx$/,
        use: ["babel-loader", "@mdx-js/loader"]
      }
    ]
  },
  plugins: [
    new HtmlWebPackPlugin({
      template: "./src/index.html",
      filename: "index.html"
    })
  ]
};
```

### Expected behaviour

I should be able to import a .mdx file

### Actual behaviour

I get this error:

```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/leifriksheim/Apps/mdx/src/Curtain/Curtain.react.mdx: Unexpected token (18:11)

  16 |     const { components, ...props } = this.props
  17 | 
> 18 |     return <MDXTag
     |            ^
  19 |              name="wrapper"
  20 |              
  21 |              components={components}>
```

Seems similar to #434

**Comment by johno** [comment] 2019-03-21 00:36
Could you also include your babel config @leifriksheim?

**Comment by leifriksheim** [comment] 2019-03-21 02:46
```
{
  "presets": ["@babel/env", "@babel/react"],
  "plugins": [
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-syntax-dynamic-import"
  ]
}
```

**Comment by leifriksheim** [comment] 2019-03-27 14:55
Any progress on this? Anything you need from me to reproduce this?

**Comment by johno** [comment] 2019-04-04 19:41
Could you please provide a minimal reproduction as a repository on GitHub so we could debug this? It feels like this is a babel parse issue since it's blowing up right at the JSX return but not sure how to further debug without something to dig into.

**Comment by johno** [comment] 2019-04-17 16:14
Going to go ahead and close this for now. Will gladly reopen with a minimal reproduction!

**Closed by johno** 2019-04-17 16:14 UTC
Labels: awaiting response
