### ISSUE TITLE
v2: Nesting of <p> inside <p>

### ISSUE THREAD

**Issue by ferdinandant** [mdx-js/mdx#1833] opened 2021-11-23 04:12 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.0-rc.2

### Steps to reproduce

[1] Open:
https://mdxjs.com/playground/

[2] Type in:
```mdx
export function Post(props) {
  return props.children;
}

<Post>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt
    eleifend blandit. Nunc elementum lacus ante, eget pretium lacus pretium non.
    Suspendisse bibendum pretium ligula vel tincidunt.
  </p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt
    eleifend blandit. Nunc elementum lacus ante, eget pretium lacus pretium non.
    Suspendisse bibendum pretium ligula vel tincidunt.
  </p>
</Post>

```

[3] Inspect element on the "run" tab
![Screen Shot 2021-11-23 at 11 05 57](https://user-images.githubusercontent.com/7868061/142969919-76945b21-9958-4a69-b57b-bacd82607d5c.png)

### Expected behavior

There shouldn't be `<p>` inside `<p>` (`<p>` followed by series of whitespaces should just generate one node of `<p>`). It will trigger `validateDOMNesting` warning in React otherwise.

Unfortunately, the above code is how prettier will prettify the following code:
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAMwFcowYBLaPABQgGcYAKDbCDOgSj2AB0o882ODCLZ+LNnQB0YABbkANgBMhUANx8Avnz4AeWgwB8fAboyGAMjjgBbPOXZE7SiApx465fAEMbwgDR4kFB0cGTConjeSg7kdGDkUADmeHAKXlJ4AKIUvngUpORKJPhpcOQECEp4AEYK3lAxMJkAciRgqQq2CCJ29WBEdFGwcIFwScJ4LMLkTnj9g1NCFHNQ0JkAyoMYVXGhteQ1VXPTK33kSUT1eABuafmJCcWwUroA9OYmeGaW1nYOdDmLjc2A8XiifhggWCoXCIlB0Vi8USKTSGWyuTsBSeJU65UqjVq9Ua6LapDxflgcwWQwa8DGE3wp1mfW8AyGzNW6zwWzoOxJdH2NUOxzsnPOl2udwUD0Kz2a70+UHeBhghhA-hAbAo0DoyFA3mwrAA7tRDQg9ShvApjd4AJ56zU1bBsgDWwg2vjgFkScGQBGtoSdLrA7pgGwwbJRyBg2CIo1QNiOSiUcCUFgal28EwAYjgbN4YAUksgQN4iDAIBqQLIYDYFAB1eTwPlsuAbC1ecg3Lx20tgQXVxKhXDUF1JAv+wMJgBWdDQGxRXQAikQIPApwogyBI9gR6WbEo0NWWIkYA2ijBZMgABwABk1ElCDZdGFL0xHd2rAEc1-Ax5IpbeHQAC0UBwGmabVkIv7kEIY7ZpOSABluCahDY5AxnGaFLnAq7rn6yHTpqMDeDUF5KFeyAAEwkS6igogAwhANhIagdAAKzVoMcAACpkZaKHbjc8YAJKND0GxgNgDgwAAgo0GwwHaXSbqEmiaEAA
```mdx
export function Post(props) {
  return props.children;
}

<Post>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt eleifend blandit. Nunc elementum lacus ante, eget pretium lacus pretium non. Suspendisse bibendum pretium ligula vel tincidunt.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt eleifend blandit. Nunc elementum lacus ante, eget pretium lacus pretium non. Suspendisse bibendum pretium ligula vel tincidunt.</p>
</Post>
```

### Actual behavior

There is `<p>` inside `<p>` (see image above)

### Runtime

Node v16

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

webpack

**Comment by ChristianMurphy** [comment] 2021-11-23 04:39
This is a duplicate of https://github.com/mdx-js/mdx/issues/1798

> This is expected behavior. It’s different from before, but I believe the new rules are in the end more sensical than the previous rules.
> See [Interleaving](https://v2.mdxjs.com/docs/what-is-mdx/#interleaving) and [Migrating](https://v2.mdxjs.com/migrating/v2/#update-mdx-files)


The cleanest approach would be to use the paragraphs given by markdown

```mdx
export function Post(props) {
  return props.children;
}

<Post>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt eleifend blandit. Nunc elementum lacus ante, eget pretium lacus pretium non. Suspendisse bibendum pretium ligula vel tincidunt.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt eleifend blandit. Nunc elementum lacus ante, eget pretium lacus pretium non. Suspendisse bibendum pretium ligula vel tincidunt.
</Post>
```

or if you want to explicitly add them as tags, this can be done by in-lining the jsx:

```mdx
export function Post(props) {
  return props.children;
}

<Post><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt eleifend blandit. Nunc elementum lacus ante, eget pretium lacus pretium non. Suspendisse bibendum pretium ligula vel tincidunt.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt eleifend blandit. Nunc elementum lacus ante, eget pretium lacus pretium non. Suspendisse bibendum pretium ligula vel tincidunt.</p></Post>
```

**Closed by ChristianMurphy** 2021-11-23 04:39 UTC
Labels: 🙋 no/question, 👯 no/duplicate

**Comment by kyleknighted** [comment] 2021-11-30 13:29
> or if you want to explicitly add them as tags, this can be done by in-lining the jsx:

> Unfortunately, the above code is how prettier will prettify the following code:

@ChristianMurphy it was mentioned that prettier does not allow for inline.

**Comment by ChristianMurphy** [comment] 2021-11-30 13:48
Again, explicitly adding the paragraph tags is not recommended. Adding a newline will do the same.

However, if you choose to do so, and want to use prettier. A prettier ignore comment can be used https://prettier.io/blog/2021/11/25/2.5.0.html#mdx
