### ISSUE TITLE
Unable to parse p tag with newline

### ISSUE THREAD

**Issue by cameronbraid** [mdx-js/mdx#2181] opened 2022-11-24 00:40 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

Examples to paste into playground 
```
<p>a
</p>
```

```
<p>
a</p>
```

### Expected behavior

Should parse fine

### Actual behavior

example.mdx
  1:1-1:5  error  Expected a closing tag for `<p>` (1:1-1:4) before the end of `paragraph`  end-tag-mismatch  mdast-util-mdx-jsx

✖ 1 error

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Other (please specify in steps to reproduce)

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by ChristianMurphy** [comment] 2022-11-24 00:51
Duplicate of https://github.com/mdx-js/mdx/issues/2172

Again:

Please see the guide on MDX syntax https://mdxjs.com/docs/what-is-mdx/#jsx
A JSX block can either be inline or block, in your example line 1 is inline, the error is correct for inline content, there is no closing tag on line 1.
You want it to be a block, to do so use:

```
<p>
a
</p>
```

**Closed by ChristianMurphy** 2022-11-24 00:51 UTC

**Comment by cameronbraid** [comment] 2022-11-24 01:05
Aah, sorry, I was upgrading from an older version of mdx which worked for this example
