### ISSUE TITLE
TypeError: this.getOptions is not a function 

### ISSUE THREAD

**Issue by jttry** [mdx-js/mdx#2054] opened 2022-05-30 08:19 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v2.1.1

### Steps to reproduce

![image](https://user-images.githubusercontent.com/18324315/170948227-6212f3ea-d19b-4e71-9dea-cb5aee7174e2.png)

### Expected behavior

no warning 

### Actual behavior

![image](https://user-images.githubusercontent.com/18324315/170948944-bd835553-254f-45ab-a55b-14b914adc5f7.png)

### Runtime

Node v16

### Package manager

npm v8

### OS

macOS

### Build and bundle tools

webpack

**Comment by timneutkens** [comment] 2022-05-30 08:45
This would generally mean you're on an old version of webpack, can you check if you're using webpack 5 👍

**Comment by padunk** [comment] 2022-06-20 01:04
I have the same issue.
Using webpack 5.73.0
![Screen Shot 2022-06-17 at 16 37 26](https://user-images.githubusercontent.com/25411350/174508216-409a1f0c-7509-47f4-941c-fbf77b1a9835.png)

**Comment by Legendree** [comment] 2022-06-20 11:42
@jttry @padunk  Downgrading to [1.6.22](https://www.npmjs.com/package/@mdx-js/loader/v/1.6.22) fixes this issue.

**Comment by wooorm** [comment] 2022-06-20 17:05
I recommend not downgrading if possible. I need a reproduction to be able to debug this.

This most likely is due to an old webpack. For more information on using MDX with CRA see: https://mdxjs.com/docs/getting-started/#create-react-app-cra.

Closing as this does not need changing in MDX. And because it is also discussed in other places, e.g., https://github.com/mdx-js/mdx/discussions/1870

**Closed by wooorm** 2022-06-20 17:05 UTC

**Comment by ruanyl** [comment] 2022-07-15 07:52
Sharing my experience of fixing this issue, not sure if that helps:

I'm working on a monorepo, it has a **storybook application** that runs on storybook@5 which uses webpack@4 internally. And also it uses `@storybook/addon-docs` that uses `@mdx-js/loader@1.x`

The problem happened when I added another **documentation application** to the monorepo that relies on `@mdx-js/loader@2.x`. It failed to run storybook and complained `this.getOptions is not a function`

I think that has something to do with how the packages are resolved, because in my monorepo case, the packages are hoisted to project root `node_modules`, and the `@mdx-js/loader@2.x` is there.

The fix:
Specify `@mdx-js/loader@1.x` in the **storybook application** `package.json`
