### ISSUE TITLE
Variables in images / links aren't parsed

### ISSUE THREAD

**Issue by maxsteenbergen** [mdx-js/mdx#2309] opened 2023-06-01 14:47 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.3

### Link to runnable example

https://stackblitz.com/github/mdx-js/.github/tree/main/sandbox-templates/mdx-evaluate-create-react-app?file=src%2FApp.js

### Steps to reproduce

I'm using mdx in a Nextjs monorepo, loading mdx from package A into package B. The mdx should load images that are placed in the same folder so basically just `![my screenshot](./screenshot.png)`.

To load the image in the other package of the monorepo, I'll have to import the image to get a generated url: 

```
import Screenshot from "./screenshot.png";
```

This returns an object that contains a `src` key, which should be used the image's actual src. Now the issue is when trying to use this variable in Markdown's image syntax. The `{variable}` code isn't replaced with its contents, but rendered as-is.
Markup like `![screenshot]({Screenshot.src})` gets transformed to 

```
<p><img src="%7BScreenshot.src%7D" alt="screenshot"></p>
```

If I use a regular HTML tag like`<img src={Screenshot.src} />`, the whole setup does work.

The same happens for links (which is basically the same syntax).

### Expected behavior

Variables in MD image & link syntax get replaced with their actual values

### Actual behavior

Variables in MD image & link syntax are flattened to their source code.

### Runtime

Node v18

### Package manager

pnpm

### OS

macOS

### Build and bundle tools

webpack, Next.js

**Comment by ChristianMurphy** [comment] 2023-06-01 14:52
Duplicate of https://github.com/mdx-js/mdx/issues/2173

**Comment by wooorm** [comment] 2023-06-01 14:53
Hi!

MDX isn’t a templating language.
Template languages use some variable syntax, expand those, and *then* the final result is some valid other language.
MDX is an actual language, which is parsed: emphasis doesn’t work in that place either. So our expressions don’t either.

**Closed by ChristianMurphy** 2023-06-01 14:52 UTC

**Comment by maxsteenbergen** [comment] 2023-06-01 15:51
Ah right, thanks for the quick note. I did see that duplicate issue but was apparently too quick to dismiss it as something different. 
Thanks for the great project!

**Comment by wooorm** [comment] 2023-06-01 20:06
Some extra thoughts:

- we *could* parse these cases and it wouldn't be technically difficult: we allow escapes (& copy; and \ -) there and those are fine, so the parsing side is OK? However, the AST: those escapes are turned into what they represent, there's just strings in the url field on an image, it would need a massive change to allow other nodes there
- We focus on frameworks like react which use braces for mostly components. These things where we could add support (url on img and a, title on img and src, class on code) are basically all dom props/html attributes that allow only strings, not components: doing this makes it easy to do things wrong

**Comment by maxsteenbergen** [comment] 2023-06-02 07:29
I think limiting this usecase to just strings is fine? You might be able to only allow string literals in those areas (img url's etc.). 

Just spitballin' here, but couldn't a rule of thumb that allows this use case be something like `Only substitutions of type: String (or a component that returns a string) are allowed if the braces are between a closing angle bracket and a open angle bracket`.

To illustrate:

```
# Title

<CompA />

{myImgSrcVariable} // ← only strings allowed here because it's between `>` and `<`

![image](myImgSrcVariable) // that means only strings are allowed here as well, preventing errors

<CompB prop={CompA} /> // Anything goes here, because it's locked between `<` and `>`
```

**Comment by remcohaszing** [comment] 2023-06-02 07:44
As a practical solution for now, you can use JSX:

```jsx
<img alt="screenshot" src={Screenshot.src} />
```

You may also be interested in [`remark-mdx-images`](https://github.com/remcohaszing/remark-mdx-images).

**Comment by wooorm** [comment] 2023-06-02 08:18
> limiting this usecase to just strings is fine

Whether something is a string or not is outside the scope of this project: MDX doesn’t “see” what’s inside those values.
So this might not be a problem, it’s just users that can optionally do things wrong.

**Comment by maxsteenbergen** [comment] 2023-06-02 08:27
I see. Well, I'd say that most MDX users are technically knowledgeable enough (or should be) to figure this out so long as there's a note in the docs. Users will always find ways to screw things up; enabling this functionality does bring MDX a lot closer to pure Markdown

**Comment by wooorm** [comment] 2023-06-02 08:44
Users being able to hurt themselves is one (small) downside. The main reason remains that the AST can’t represent this (see https://github.com/mdx-js/mdx/issues/2309#issuecomment-1572702231). I also don’t buy that this is a good feature. I don’t see “closer to pure Markdown”, because markdown doesn’t allow emphasis there either. It only allows escapes. There is also a very good alternative already, use JSX: `<img alt="screenshot" src={Screenshot.src} />`
