### ISSUE TITLE
Broken link in Get-started page of docs

### ISSUE THREAD

**Issue by Shwetzksk** [mdx-js/mdx#2366] opened 2023-10-10 05:33 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Effecting the docs

### Steps to reproduce

1. ### Visit this page: https://mdxjs.com/docs/getting-started/

2. ### Scroll to bottom
![image](https://github.com/mdx-js/mdx/assets/59056624/9bcf2cd0-0e57-4351-8b2c-32fd3013da1b)

3. ### The highlighted in red is leading to 404 page where as marked in green is working correctly.

### Red marked "Using Mdx"  is expected to navigate user to "https://mdxjs.com/docs/using-mdx/"

<br/>

![image](https://github.com/mdx-js/mdx/assets/59056624/27d64c81-208b-4d42-9220-21b9a483666a)

### Clicking on red marked "Using Mdx" is leading to link "https://mdxjs.com/docs/getting-started/using-mdx/"

![image](https://github.com/mdx-js/mdx/assets/59056624/a5014594-7ab9-4a99-ab2d-8e03cdc90984)

**Comment by Shwetzksk** [comment] 2023-10-10 05:50
It seems like this issue is fixed in the code but hasn't been deployed on the prod.

**Comment by ChristianMurphy** [comment] 2023-10-10 13:10
Duplicate of #2365

**Closed by ChristianMurphy** 2023-10-10 13:10 UTC
