### ISSUE TITLE
`@mdx-js/loader` doesn't provide `react` as peer dep

### ISSUE THREAD

**Issue by nicholaschiang** [mdx-js/mdx#1917] opened 2022-01-26 02:12 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@mdx-js/loader@npm:1.6.22

### Link to runnable example

https://github.com/nicholaschiang/rmc

### Steps to reproduce

1. Install `@mdx-js/loader` using Yarn v2.
2. Notice that Yarn gives the following warning:

```
@mdx-js/loader@npm:1.6.22 doesn't provide react (p12550), requested by @mdx-js/react
```

I came across this issue when setting up Storybook for my [RMC](https://github.com/nicholaschiang/rmc) project; you should be able to simply clone that repository and `yarn install` to see the problem.

### Expected behavior

`@mdx-js/loader` should specify `react` as a peer dependency to prevent these warnings when using Yarn v2's new plug-n-play methodology.

### Actual behavior

Yarn gives the following error message when installing (during the "Resolution step"):

```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @mdx-js/loader@npm:1.6.22 doesn't provide react (p12550), requested by @mdx-js/react
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 1s 852ms
```

### Runtime

Node v16

### Package manager

yarn v2

### OS

Linux

**Comment by wooorm** [comment] 2022-01-26 08:44
Duplicate of GH-1600

**Closed by wooorm** 2022-01-26 08:44 UTC
Labels: 👯 no/duplicate, 👎 phase/no
