### ISSUE TITLE
extra p tag is add when using 2.0.0-next.9

### ISSUE THREAD

**Issue by hxlhxl** [mdx-js/mdx#1595] opened 2021-07-23 06:23 UTC
### Subject of the issue

extra p tag is add when using 2.0.0-next.9

### Your environment

*   **OS**: Windows
*   **Packages**:  "@mdx-js/mdx": "2.0.0-next.9"
*   **Env**:  v12.20.0

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5368975/126744381-3aa5d8c7-68b1-4e47-a4c1-b94997247245.png)

### Expected behaviour

the same tag as pure html

### Actual behaviour

extra p tag was added

**Comment by mvasilkov** [comment] 2021-07-23 18:15
A duplicate of https://github.com/mdx-js/mdx/issues/1451 I guess.

**Closed** 2021-07-23 20:18 UTC
Labels: 🐛 type/bug
