### ISSUE TITLE
[v2] Heading custom ID extended syntax support

### ISSUE THREAD

**Issue by jerelmiller** [mdx-js/mdx#1279] opened 2020-09-26 06:04 UTC
Hey there 👋 . First off, thanks so much for all the hard work on v2! I'm really excited to start using it.

I have an interesting situation where we need to be able to define custom IDs for headings generated from markdown. I am part of a team in the process of moving our old docs site written in drupal over to Gatsby/MDX. We have lots and lots of pages within our docs site (5000+) and many of them link to each other. Because we want to maintain backwards compatibility with the existing site, we want to maintain the existing `id` attributes on headings so that our links don't break.

### Problem

In v1, it appears that the [extended syntax for custom heading IDs](https://www.markdownguide.org/extended-syntax/#heading-ids)  worked correctly when using the [`gatsby-remark-autolink-headers`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-autolink-headers). I suspect this was a result of how the AST was parsed in v1.

Take the following example:

```markdown
# A heading {#custom-id}
```

This would result in the AST looking something like the following:

```js
{
  type: 'heading',
  depth: 2,
  children: [
    {
      type: 'text',
      value: 'A heading {#custom-id}',
    }
  ],
}
```

Note here how the custom ID was part of the `value` of the `text` child. It appears the `gatsby-remark-autolink-headers` plugin expects this as part of the AST so that it can update the `h` tag with the custom ID.

With the much more robust parsing in v2 (which is AWESOME), the same node is parsed into the following:

```js
{
  type: 'heading',
  depth: 3,
  children: [
    {
      type: 'text',
      value:
        'A heading',
    },
    {
      type: 'mdxSpanExpression',
      value: '#custom-id',
    },
  ],
}
```

Because of this, unfortunately it causes issues when compiling to into JSX because it results in an expression like the following:

```js
<h1>{`A heading`}
{#test}</h1>
```

### Alternatives

I'm not really sure what I expect the behavior to be here. I can understand why the parser would parse this heading expression as it does. Writing the heading as a regular JSX header works as intended:

```js
// Works
<h1 id="custom-id">A heading</h1> 
```

However this is a bit of a bummer as we lose some readability because of this.

Would it be possible to support the custom ID syntax on headings to support this use case?

**Comment by wooorm** [comment] 2020-09-26 10:10
Heya! 👋 thanks for the kind words!

As another alternative: could the gatsby plugin (or a gatsby-mdx specific one) perhaps support the new AST?

**Comment by jerelmiller** [comment] 2020-09-27 05:53
Great question! This would likely fall under the [gatsby-remark-autolink-headers](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-autolink-headers) package since its currently handling the AST parsing/manipulating for header IDs. I'd be happy to open an issue over there. Since its an official Gatsby plugin and since Gatsby plans to support MDX v2, I assume that plugin would need to work. I wasn't sure if this was something that should be solved at the parse/AST level or the transform/compile level.

Thanks so much for replying so quickly!

**Comment by wooorm** [comment] 2020-09-29 12:53
I don’t think it should be changed here, as it’s by design: `{...}` is an expression here. For example, `{1 + 1}` could output 2.

**Comment by jerelmiller** [comment] 2020-10-01 17:54
That makes sense and imagine that leaves little room for surprising behavior. Thanks for advising!

**Comment by wooorm** [comment] 2020-11-13 17:09
I’m going to close this as it is an intended change: to move closer to JSX.

I don’t see why that gatsby plugin does work that isn‘t in its readme, anyway: MDX has remark and rehype plugins, where you can do custom IDs in code, and if you want them in content, well, there are other remark plugins that allow that. Or you can use JSX in MDX?

**Closed by wooorm** 2020-11-13 17:09 UTC
Labels: 🔍 status/open, 🦋 type/enhancement
