### ISSUE TITLE
BUG: parse error 

### ISSUE THREAD

**Issue by janryWang** [mdx-js/mdx#318] opened 2018-11-20 04:33 UTC
### Subject of the issue

If the callback function of the component props contains some spaces, an error will be reported.

Describe your issue here.  Remember, this is _not_ a place to ask questions.  For that, go to [spectrum](https://spectrum.chat/mdx)

### Your environment

*   Name and version of operating system
*   Names and version of required packages
*   Version of node, npm, yarn, or names and versions of browser

### Steps to reproduce

https://codesandbox.io/s/oomowor24q

### Expected behaviour

Should not be given an error

### Actual behaviour

Adjacent JSX elements must be wrapped in an enclosing tag (4:0)

**Comment by stephanschubert** [comment] 2018-11-20 08:48
Another parse error I noticed in the given example:

* Change opening/closing `h1` tag in the template string `mdx` to another one like `p` results in:

```
Expected corresponding JSX closing tag for <MDXTag> (7:2)
```

https://codesandbox.io/s/43wq9nn627

**Comment by janryWang** [comment] 2018-11-21 04:39
@silvenon

**Comment by silvenon** [comment] 2018-11-21 07:57
I think this is a duplicare. Right now our parser can’t follow the block after multiple newlines, it starts parsing it as an independent item (like markdown paragraphs).

**Comment by janryWang** [comment] 2018-11-21 08:36
JSXOpeningElement parsing need to distinguish

**Comment by silvenon** [comment] 2018-11-21 09:10
> JSXOpeningElement parsing need to distinguish

@janryWang what do you mean? I didn't understand.

@stephanschubert also a known issue, tags like `p` and `a` are treated differently in markdown, so remark doesn't parse them the same way as `div`.

**Comment by johno** [comment] 2019-02-15 16:44
Thanks for creating a reproduction! Going to close this since we can track progress in #195.

**Closed by johno** 2019-02-15 16:44 UTC
Labels: bug
