### ISSUE TITLE
Expected a closing tag for `<td>`before the end of `paragraph`

### ISSUE THREAD

**Issue by BrunoQuaresma** [mdx-js/mdx#2063] opened 2022-06-17 19:42 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.1.1

### Steps to reproduce

Paste the following MDX code on [MDX Playground](https://mdxjs.com/playground/):

https://gist.githubusercontent.com/BrunoQuaresma/b25c0a374129d4881ed9307bfba3de75/raw/d0ccb78563dba813abee0b3268111f2a8c4f1245/some.mdx

### Expected behavior

It should not fail.

### Actual behavior

It is throwing an error: Expected a closing tag for `<td>` (114:9-114:13) before the end of `paragraph`.

**Comment by ChristianMurphy** [comment] 2022-06-17 19:55
Duplicate of https://github.com/mdx-js/mdx/issues/1798 and https://github.com/mdx-js/mdx/issues/2002

This is due to the rules of interleaving https://mdxjs.com/docs/what-is-mdx/#interleaving

Another way you could achieve the effect you want, is wrapping the JSX block in `{}`
<details>
<summary>
example
</summary>

````md
---
title: Environment variables
description:
  Learn how to work with CODER_* environment variables inside workspaces.
---

Coder injects a standard set of environment variables that allow you to access
contextual information about your workspace.

To obtain a list of environment variables and their values, launch the
**Terminal** via the Coder Dashboard and run:

```console
env | grep CODER_
```

## Available environment variables


{<table>
    <tr>
        <th>Environment variable</th>
        <th>Description</th>
    </tr>
    <tr>
        <td><code>CODER_ASSETS_ROOT</code></td>
        <td>The directory where coder adds Coder-specific assets during
            workspace creation, such as the <code>coder-cli</code> binary</td>
    </tr>
    <tr>
        <td><code>CODER_CPU_LIMIT</code></td>
        <td>The CPU core limit given to your workspace</td>
    </tr>
    <tr>
        <td><code>CODER_IMAGE_DIGEST</code></td>
        <td>The content-addressable identifier for your image</td>
    </tr>
    <tr>
        <td><code>CODER_IMAGE_TAG</code></td>
        <td>The image tag used to create your workspace</td>
    </tr>
    <tr>
        <td><code>CODER_IMAGE_URI</code></td>
        <td>The URI of the image used to build the workspace</td>
    </tr>
    <tr>
        <td><code>CODER_MEMORY_LIMIT</code></td>
        <td>The memory limit given to your workspace in GB</td>
    </tr>
    <tr>
        <td><code>CODER_ORGANIZATION_ID</code></td>
        <td>The ID of the organization to which the workspace belongs.</td>
    </tr>
    <tr>
        <td><code>CODER_RUNTIME</code></td>
        <td>The container runtime used to start the workspace (either
        <code>kubernetes/default</code> or <code>kubernetes/sysbox</code>
        if the workspace is a CVM</td>
    </tr>
    <tr>
        <td><code>CODER_URL</code></td>
        <td>The base URL of your Coder deployment</td>
    </tr>
    <tr>
        <td><code>CODER_USER_EMAIL</code></td>
        <td>Your email address</td>
    </tr>
    <tr>
        <td><code>CODER_USERNAME</code></td>
        <td>Your user name</td>
    </tr>
    <tr>
        <td><code>CODER_WORKSPACE_ID</code></td>
        <td>The unique ID of your workspace</td>
    </tr>
    <tr>
        <td><code>CODER_WORKSPACE_NAME</code></td>
        <td>The name of your workspace</td>
    </tr>
    <tr>
        <td><code>CODER_WP_NAME</code></td>
        <td>The name of the workspace provider hosting the workspace</td>
    </tr>
</table>}



## Other variables

Coder uses the following environment variables for its internal operation:

> **Important**: These variables may be modified or removed in future releases
> without prior notice and are not covered by Coder's backward compatibility
> policy. These are documented here for your information only.

{<table>
    <tr>
        <th>Environment variable</th>
        <th>Description</th>
    </tr>
    <tr>
        <td><code>CODER_AGENT_TOKEN</code></td>
        <td>The token used by the <a href="../setup/architecture.md">Coder Agent</a>
            to authenticate with <code>coderd</code>. The Coder Agent handles
            tunnelled connections, collects workspace statistics (such as
            processor and memory utilization), and manages programs, such as
            editors.</td>
    </tr>
    <tr>
        <td><code>CODER_AGENT_URL</code></td>
        <td>The URL that the <code>coder agent</code> process uses
            to connect to <code>coderd</code>. If this is not set, the agent
            will connect to <code>CODER_URL</code> instead, enabling the
            <code>coder agent</code> and <code>coder</code> command-line tool
            to connect to different installations.</td>
    </tr>
    <tr>
        <td><code>CODER_BOOTSTRAP_SCRIPT</code></td>
        <td>The script used to initiate the workspace startup sequence when the
            <a href="../admin/workspace-management/self-contained-builds.md">
            self-contained workspace builds</a> feature is active; begins by
             downloading the "bootstrap agent" from the <code>coderd</code>
             process.</td>
    </tr>
</table>}
````

</details>

**Closed by ChristianMurphy** 2022-06-17 19:55 UTC
