### ISSUE TITLE
Suggestion: parse code meta text as JSX attributes

### ISSUE THREAD

**Issue by redallen** [mdx-js/mdx#1192] opened 2020-07-28 15:44 UTC
Problem:
``````
```js key="value with spaces"
```
``````
gets parsed as:
```json
{
  "key": "\"value",
  "with": true,
  "spaces\"": true
}
```

I've implemented my own `mdx-ast-to-mdx-hast.js` that uses `acorn`, but of course `babel` could be used to be more consistent with MDX.
```js
const acorn = require('acorn');
const jsx = require('acorn-jsx');
const jsxParser = acorn.Parser.extend(jsx());

const parseJSXAttributes = jsx => {
  const properties = {};
  const jsxAttributes = jsxParser.parse(jsx)
    .body[0]
    .expression
    .openingElement
    .attributes;

  jsxAttributes.forEach(attr => {
    properties[attr.name.name] = attr.value ? attr.value.value : true;
  });

  return properties;
}

if (node.meta) {
  try {
    Object.entries(parseJSXAttributes(`<Component ${node.meta} />`))
      .forEach(([key, val]) => {
        properties[key] = val;
      }); 
  }
  catch(error) {
    file.fail(`Error parsing "${node.meta}": ${error}`);
  }
}
```

**Comment by wooorm** [comment] 2020-07-28 16:07
Thanks, but duplicate of https://github.com/mdx-js/mdx/issues/702!

**Closed by wooorm** 2020-07-28 16:07 UTC
Labels: 🔍 status/open, 🦋 type/enhancement
