### ISSUE TITLE
Multiline footnotes broken in 1.6.1

### ISSUE THREAD

**Issue by Eyas** [mdx-js/mdx#1052] opened 2020-05-02 18:33 UTC
### Subject of the issue

Given the Markdown:

```md
Hey there [^1]

[^1]:
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
  incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
  nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
  eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt
  in culpa qui officia deserunt mollit anim id est laborum.
```

`@mdx-js/mdx@1.5.8` used to transform this into an AST where the "Lorem ipsum" paragraph is part of the footnote. `@mdx-js/mdx@1.6.1` transofrms this into an empty footnote, and the paragraph is just rendered as text.

### Your environment

*   **OS**: 
*   **Packages**: @mdxjs/mdx@1.5.8 -- Tried both in:
    * gatsby via latest gatsby-remark-mdx, and
    * fork of ast-explorer with 1.5.8 vs 1.6.1.
    * old (correct) behavior can be seen in astexplorer.net
*   **Env**: 
  * Tried with Yarn and NPM

### Steps to reproduce

Use this markdown:

```md
Hey there [^1]

[^1]:
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
  incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
  nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
  eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt
  in culpa qui officia deserunt mollit anim id est laborum.
```

### Expected behaviour

Renders "Hey there(1)" with a footnote at the bottom containing entire paragraph.

Prettier agrees and reformats footnote with very long paragraph after it into this format.

### Actual behaviour

Renders:

"Hey there(1)

Lorem ipsum dolor sit amet,...

[1]: (empty)"

**Comment by Eyas** [comment] 2020-05-02 19:24
What's weird is that mdx outsources footnote handling to `remark-footnotes`, but remark footnotes does (at least claims to) support multiline footnotes ([Docs](https://github.com/remarkjs/remark-footnotes)).

**Comment by wooorm** [comment] 2020-05-02 19:41
Remark used to come with a footnote option, which is now a separate plugin, with a bit of a different syntax. Maybe that’s related?

**Comment by Eyas** [comment] 2020-05-02 19:44
Yeah, I think it's this. Opened remarkjs/remark-footnotes#1

remark-footnotes doesn't like mutliline footnotes where the first line is blank. E.g. a footnote that is one long paragraph.

But mdx used to be okay with that.

I think supporting it is the right solution here, since prettier formatting will turn a long-single-paragraph footnote into the format you see above.

**Comment by daneden** [comment] 2020-06-07 09:55
Came here to +1! Reproducible on my site as well.

**Comment by wooorm** [comment] 2020-06-07 15:20
@daneden It’s unfortunate that this happened in a patch on the MDX-side (1.5.9), sorry about that.
On the remark and remark-footnotes side, it did happen in a major, and it’s not something I’m interested in changing again (see the linked issue: https://github.com/remarkjs/remark-footnotes/issues/1, which includes a discussion w/ prettier folks). Footnotes used to be based on the weird PHP Markdown Extra footnote style, but are now based on Pandoc footnote style, which I’m under the impression is more popular, and hence makes more sense to follow.

**Comment by wooorm** [comment] 2020-11-13 16:00
I’m going to close this because it’s not something *in* this package, and it’s not going to change in remark-footnotes either. Sorry again for breaking your build!

**Closed by wooorm** 2020-11-13 16:00 UTC
Labels: 🐛 type/bug, 🔍 status/open
