### ISSUE TITLE
alerts provide distinctive styling for significant content

### ISSUE THREAD

**Issue by wqcstrong** [mdx-js/mdx#2560] opened 2024-11-25 02:57 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=issues) and [discussions](https://github.com/orgs/mdx-js/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

`remark-gfm` now don't support the [New Markdown Extension](https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/).

This is a discussion: https://github.com/orgs/community/discussions/16925.

### Current solutions

I can create a react component to support it.

### Proposed solutions

I can enjoy those alert styles directly in `.mdx` with `remark-gfm`.

**Comment by remcohaszing** [comment] 2024-11-25 07:42
Duplicate of https://github.com/remarkjs/remark-gfm/issues/53

**Closed by remcohaszing** 2024-11-25 07:42 UTC
Labels: 🤞 phase/open

**Comment by wqcstrong** [comment] 2024-11-25 07:49
> Duplicate of [remarkjs/remark-gfm#53](https://github.com/remarkjs/remark-gfm/issues/53)

Thanks!
