### ISSUE TITLE
monorepo - MDXProvider doesn't apply custom components for MDX files from different workspace

### ISSUE THREAD

**Issue by wonskarol** [mdx-js/mdx#615] opened 2019-06-24 14:07 UTC
Hey,

today I have ran into issue with MDX provider. Let me first explain my setup:
I've monorepo with following structure: 
```
packages
- button
-- Button.notes.mdx
-- Changelog.md
...
webapps
- design-system
-- src 
--- index.mdx
```
And I would like to import `Button.notes.mdx` and `Changelog.md` in `index.mdx`:
```
import Changelog from "@company/button/CHANGELOG.md";
import Notes from "@company/button/Button.notes.mdx";

# Button notes

some paragraph

1. some
2. list

<Notes />

# Button changelog

<Changelog />

```
This is part of my webpack config (`webapps/design-system/config/webpack.config.js`):
```
  {
  test: /\.mdx?$/,
  include: [
    path.resolve(__dirname, "../src"),
    path.resolve(__dirname, "../../../packages/button"),
  ],
  use: [
    { loader: "babel-loader" },
    {
      loader: "@mdx-js/loader",
      options: {
        remarkPlugins: [images, emoji],
      },
    },
  ],
},
```
And finally my root React component:
```
import React from "react";
import { render } from "react-dom";
import { ThemeProvider } from "styled-components";
import { MDXProvider } from "@mdx-js/react";
import { BrowserRouter as Router, Route } from "react-router-dom";

import { routes } from "./routes";
import {
  GlobalStyle,
  Container,
  LeftPanel,
  RightPanel,
  Logo,
  Menu,
  theme,
} from "./layout/index";
import { P, H1, H2, H3, A, Img, Li } from "./mdxComponents/index";

const App = () => {
  const mdxComponents = {
    p: P,
    h1: H1,
    h2: H2,
    h3: H3,
    h4: H3,
    h5: H3,
    h6: H3,
    a: A,
    img: Img,
    li: Li,
  };

  return (
    <>
      <GlobalStyle />
      <Router>
        <ThemeProvider theme={theme}>
          <MDXProvider components={mdxComponents}>
            <Container>
              <LeftPanel>
                <Logo />
                <Menu />
              </LeftPanel>
              <RightPanel>
                {routes.map((route, index) => (
                  <Route
                    key={index}
                    path={route.path}
                    exact={route.exact}
                    component={route.component}
                  />
                ))}
              </RightPanel>
            </Container>
          </MDXProvider>
        </ThemeProvider>
      </Router>
    </>
  );
};

render(<App />, document.getElementById("root"));
```
So the issue is that only markdown syntax from in `index.mdx` is rendered with custom components (green boxes), paragraphs and list from `<Notes/>` and `<Changelog/>` remains default. 
<img width="629" alt="Screenshot 2019-06-24 at 15 54 57" src="https://user-images.githubusercontent.com/5656856/60025099-3e3f2880-9699-11e9-9fef-b483710bdf30.png">
Do you see any errors in my setup? 
If I copy eg. `Button.notes.mdx` next to `index.mdx` and import it with relative path:
```
import Notes from "../Button.notes.mdx";
```
it works as expected. 
Not sure if it makes difference, but packages in `node_modules` are symlinked (I mean package `node_modules/@company/button`). 

Thanks for help! 

---
Edit:
After removing `node_modules` and installing all dependencies again, it started to work 😮 
My setup seems to be fine. Issue can be closed. 

BTW. Your project is so cool! 🙇

**Comment by johno** [comment] 2019-07-11 15:29
> Edit:
> After removing node_modules and installing all dependencies again, it started to work 😮
> My setup seems to be fine. Issue can be closed.

Going to go ahead and close this since you've got it sorted!

> BTW. Your project is so cool! 🙇

💟💟💟

**Closed by johno** 2019-07-11 15:29 UTC

**Comment by jeffplloyd** [comment] 2024-03-18 18:50
I hate to bring an old closed thread back, but I have a mono repo set up similar to above. I'm linking projects together with lerna. I am importing the MDX files form another package in the lerna monorepo. The React app runs fine locally and MDXProvider component overrides apply. It's when I build the React app and deploy or preview the build in Vite that the MDXProvider component overrides don't apply. I've narrowed it down that the issue is with the build and the MDX files are imported from an external package. Can anyone provide any help?

**Comment by ChristianMurphy** [comment] 2024-03-18 21:23
Welcome @jeffplloyd!
Sorry you ran into a spot of trouble, happy to help where possible.

Please open a new discussion with the context of your project. https://github.com/orgs/mdx-js/discussions/new?category=q-a

This issue is 5 years old, 3 major versions behind, and likely using a different build stack than yours.
All of that information will be needed to help.
There's a great guide on the site which helps with crafting questions others can help you with https://mdxjs.com/community/support/

I'm closing and locking this outdated issue, but happy to help on discussions!
