### ISSUE TITLE
2.0.0-next.9 will wrap `mdxJsxFlowElement`s in `paragraph` when it's a line

### ISSUE THREAD

**Issue by rnarkk** [mdx-js/mdx#1488] opened 2021-03-19 10:32 UTC
Input:

```html
<h1>
  Test
</h1>

<h2>Test</h2>
```

Output (`position`s removed):

```json
{
  "type": "root",
  "children": [
    {
      "type": "mdxJsxFlowElement",
      "name": "h1",
      "attributes": [],
      "children": [
        {
          "type": "paragraph",
          "children": [
            {
              "type": "text",
              "value": "Test",
            }
          ],
        }
      ],
    },
    {
      "type": "paragraph",
      "children": [
        {
          "type": "mdxJsxTextElement",
          "name": "h2",
          "attributes": [],
          "children": [
            {
              "type": "text",
              "value": "Test",
            }
          ],
        }
      ],
    },
  ]
}
```

This is a variation of the unwanted `p` layers problem #1451.

**Comment by ChristianMurphy** [comment] 2021-03-22 14:19
I'm not seeing the variation to this? It looks like a duplicate of https://github.com/mdx-js/mdx/issues/1451 with the beta number changed?
Closing this for now, as it's unclear that it is a distinct issue.

**Closed by ChristianMurphy** 2021-03-22 14:19 UTC
Labels: 🐛 type/bug, 🔍 status/open
