### ISSUE TITLE
Can’t auto display images using import syntax

### ISSUE THREAD

**Issue by borisrorsvort** [mdx-js/mdx#291] opened 2018-10-17 14:09 UTC
I’m trying to import images from a CRA app using the recommandation static image import in webpack. I’ve tried many solutions but none worked for me. Also it seems you can’t define static const and display them either. Am I getting this completely wrong? I can’t believe i’m the only one ^^

```js
import img from "img.png";

![]({img})

// renders:  <img scr="{img}" /> and completely escapes the js code
```

**Comment by silvenon** [comment] 2018-10-17 14:14
We haven't solved interpolation yet. 😕 Closing as duplicate of #165.

**Closed by silvenon** 2018-10-17 14:14 UTC
Labels: duplicate
