### ISSUE TITLE
Line breaks in block-level JSX create unexpected whitespace in the output

### ISSUE THREAD

**Issue by thorn0** [mdx-js/mdx#843] opened 2019-11-15 18:13 UTC
### Subject of the issue

As we're trying to improve Prettier's support of MDX, I'm trying to understand its syntax better. So far it looked like block-level JSX is supposed to be 100% React-compatible for it to be possible to copy-paste React code from JS to MDX (also it would allow Prettier to use the same code for formatting JSX that it uses for JSX in JS). But I found an incompatibility that breaks this use case, namely: _a line break between an element and text doesn't create whitespace in the output in React but does in MDX_. Posting here after [asking on Spectrum](https://spectrum.chat/mdx/general/whitespace-in-block-level-jsx~38817f54-db82-4971-be9e-584e1c4d20ff).

### Your environment

The official playground https://mdxjs.com/playground/

### Steps to reproduce

```jsx
<b>foo</b>
bar
```

### Expected behaviour

Should be rendered as

> **foo**bar

https://codepen.io/thorn0/pen/NWWEaoo

### Actual behaviour

Is rendered as

> **foo** bar

**Comment by wooorm** [comment] 2020-04-21 14:16
That does align with what happens for:

```
*foo*
bar
```

---

I think both the actual behavior and expected behavior are weird btw, I think the `<b/>` should be seen as a JSX block with a paragraph, and the `bar` as another paragraph:

> <b>foo</b>
>
> bar

Why that should happen is clearer with this example:

```
<h2>foo</h2>
bar
```

(I don’t think we should check tag names to determine if something is a block, rather, as there’s no text before `<h2>`, and no text after `</h2>, it should be a block).

**Comment by thorn0** [comment] 2020-04-21 14:27
> I think both the actual behavior and expected behavior are weird btw, I think the <b/> should be seen as a JSX block with a paragraph, and the bar as another paragraph:

Agree. This would make a lot of sense.

**Comment by wooorm** [comment] 2020-04-21 15:42
Luckily I’m working on exactly that! 😏 More soon!

**Comment by wooorm** [comment] 2020-11-13 14:56
forgot to mention it here, but this landed for v2, on the `next` branch

**Comment by wooorm** [comment] 2020-12-18 16:04
Hi all! I’m going to close this as it landed on the `main`, the (now default) branch we’re using to gear up to the MDX@2 release.

The reason is so that it’s more clear which issues still need to be solved already and don’t require further work.

Expect another `next` release soonish, which might include it, or maybe it’s already released as a beta!

For more info, see <https://github.com/mdx-js/mdx/issues/1041>.

**Closed by wooorm** 2020-12-18 16:04 UTC
Labels: 🐛 type/bug, 🔍 status/open
