### ISSUE TITLE
`remark-mdx` does not work with `remark@13`

### ISSUE THREAD

**Issue by MatthewCaseres** [mdx-js/mdx#1341] opened 2020-11-18 00:50 UTC
### Subject of the issue

I am unable to replicate the "Transform Content section of the documentation. https://mdxjs.com/advanced/transform-content

### Your environment

*   Windows 10
*   see package.json in repo
*   node v12.18.2

### Steps to reproduce

https://github.com/MatthewCaseres/mdx-reproduction

### Expected behaviour

I was trying to follow the example here: https://mdxjs.com/advanced/transform-content. I was expecting there to exist a leaf of type import as is shown in the docs

### Actual behaviour

![image](https://user-images.githubusercontent.com/43053796/99467840-d54af700-2904-11eb-85e1-273d3d9c9571.png)

**Comment by wooorm** [comment] 2020-11-18 07:44
Thanks for the reproduction, @MatthewCaseres!

remark@13 does not work with remark-mdx yet. You can either downgrade to use remark@12 for now. Or you can use `@mdx-js/mdx` directly, which includes `remark-mdx` and supports passing `remarkPlugins`.
What to do, depends on what you want to do!

**Comment by MatthewCaseres** [comment] 2020-11-18 12:37
Thanks! I'm trying to build a plugin and it seems like I can iterate and check my work faster with a node script. In my current nextjs project I have to stop and restart the server to rebuild the MDXAST and I can't output the transformed stuff to a file for inspection.

I might only need the markdown nodes (I'm modifying headers), I was just surprised I couldn't reproduce the docs. Thanks for the speedy reply!

**Comment by wooorm** [comment] 2020-11-18 14:01
A node script can also use `mdx-js/mdx`!

**Comment by wooorm** [comment] 2020-12-18 16:21
Hi all! I’m going to close this as it landed on the `main`, the (now default) branch we’re using to gear up to the MDX@2 release.

The reason is so that it’s more clear which issues still need to be solved already and don’t require further work.

Expect another `next` release soonish, which might include it, or maybe it’s already released as a beta!

For more info, see <https://github.com/mdx-js/mdx/issues/1041>.

**Closed by wooorm** 2020-12-18 16:21 UTC
Labels: 🐛 type/bug, 🔍 status/open
